arch:
  - arm64

env:
  global:
  - IMGNAME_FRONTEND=chetanyaag/ui
  - IMGNAME_BACKEND=chetanyaag/rest-api
  - USERNAME=chetanyaag
  - DHUB_PASS=dckr_pat_DtBgxqDxJG2XGK5KhffuiU8XWvo

services:
  - docker

before_install:
- docker image build -t "${IMGNAME_FRONTEND}:${TRAVIS_COMMIT}" frontend/.
- docker image build -t "${IMGNAME_BACKEND}:${TRAVIS_COMMIT}" restapi/.

script:
 - dig +short myip.opendns.com @resolver1.opendns.com
 - echo "here i am here"

after_success:
- docker login -u chetanyaag -p dckr_pat_DtBgxqDxJG2XGK5KhffuiU8XWvo
- docker push "${IMGNAME_FRONTEND}:${TRAVIS_COMMIT}"
- docker push "${IMGNAME_BACKEND}:${TRAVIS_COMMIT}" 
