arch:
  - arm64

env:
  - IMGNAME=chetanyaag/ui:three
  - USERNAME=chetanyaag
  - DHUB_PASS=dckr_pat_DtBgxqDxJG2XGK5KhffuiU8XWvo

services:
  - docker

before_install:
- cd frontend
- echo $IMGNAME
- docker image build -t $IMGNAME . 

script:
#TravisCI seems to be coming in on undocumented IP addresses.

 - dig +short myip.opendns.com @resolver1.opendns.com
 - echo "here i am here"

after_success:
- echo $IMGNAME
- docker login -u chetanyaag -p dckr_pat_DtBgxqDxJG2XGK5KhffuiU8XWvo
- docker push $IMGNAME
# - echo "${SSH_KEY}" |  base64 --decode > /tmp/ssh_rsa
# - chmod 600 /tmp/ssh_rsa
# - ssh -o "StrictHostKeyChecking no" pi@${IPADDR} -i /tmp/ssh_rsa "echo test > test.log"
# - ssh -o "StrictHostKeyChecking no" pi@${IPADDR} -i /tmp/ssh_rsa "cd ${INSTALL_LOCATION} && git pull ${TRAVIS_BUILD_WEB_URL} && docker image build -t ${IMGNAME} ${INSTALL_LOCATION}/. && docker push ${IMGNAME} && docker stop discordbot; docker rm discordbot; docker run --name discordbot --restart always -d -e TOKEN=${TOKEN} ${IMGNAME}"