apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7.0.11-alpine

---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: frontend-deployment
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: frontend
#   template:
#     metadata:
#       labels:
#         app: frontend
#     spec:
#       containers:
#       - name: frontend
#         image: chetanyaag/ui:031fa0a7b6ff1a49939a808c0cedbac060a8cdd8
#         ports:
#         - containerPort: 3000

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: chetanyaag/ui:031fa0a7b6ff1a49939a808c0cedbac060a8cdd8
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "1024Mi"
            cpu: "1000m"
          limits:
            memory: "2048Mi"
            cpu: "2000m"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restapi-app
  template:
    metadata:
      labels:
        app: restapi-app
    spec:
      containers:
      - name: restapi-app
        image: chetanyaag/restapi:031fa0a7b6ff1a49939a808c0cedbac060a8cdd8 
        command: ["gunicorn", "--bind", "0.0.0.0:8000", "tutorial.wsgi"]
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: restapi
spec:
  selector:
    app: restapi-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer



---
apiVersion: v1
kind: Service
metadata:
  name: celery
spec:
  selector:
    app: celery
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 80  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery
  template:
    metadata:
      labels:
        app: celery
    spec:
      containers:
        - name: celery
          image: chetanyaag/restapi:031fa0a7b6ff1a49939a808c0cedbac060a8cdd8  
          command: ["celery", "--app=tutorial", "worker", "-l", "INFO"]

