apiVersion: apps/v1
kind: Deployment
metadata:
  name: restapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restapi
  template:
    metadata:
      labels:
        app: restapi
    spec:
      containers:
      - name: restapi
        image: chetanyaag/restapi:three  
        command: ["gunicorn", "--bind", "0.0.0.0:8000", "tutorial.wsgi"]
        ports:
        - containerPort: 8000
        volumeMounts:
            - mountPath: /app/
              name: restapi-volume
      volumes:
        - name: restapi-volume
          hostPath:
            path: /home/chetanyaagrawal/kalpanic/restapi
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: restapi-service
# spec:
#   selector:
#     app: restapi
#   ports:
#     - protocol: TCP
#       port: 8000
#       targetPort: 8000
#   type: LoadBalancer
