apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7.0.11-alpine
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: chetanyaag/ui:two  # Update with the actual image and tag
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: /usr/src/app/
              name: frontend-volume
      volumes:
        - name: frontend-volume
          hostPath:
            path: /home/chetanyaagrawal/kalpanic/frontend
---
apiVersion: v1
kind: Service
metadata:
  name: restapi
spec:
  selector:
    app: restapi
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restapi
  template:
    metadata:
      labels:
        app: restapi
    spec:
      containers:
        - name: restapi
          image: chetanyaag/restapi:three   # Update with the actual image and tag
          command: ["gunicorn", "--bind", "0.0.0.0:8000", "tutorial.wsgi"]
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: /app/
              name: restapi-volume
      volumes:
        - name: restapi-volume
          hostPath:
            path: /home/chetanyaagrawal/kalpanic/restapi
---
apiVersion: v1
kind: Service
metadata:
  name: celery
spec:
  selector:
    app: celery
  ports:
    - protocol: TCP
      port: 80  # Change this to the desired port for Celery
      targetPort: 80  # Change this to the desired port for Celery
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery
  template:
    metadata:
      labels:
        app: celery
    spec:
      containers:
        - name: celery
          image: chetanyaag/restapi:three   # Update with the actual image and tag
          command: ["celery", "--app=tutorial", "worker", "-l", "INFO"]
          volumeMounts:
            - mountPath: /app/
              name: celery-volume
      volumes:
        - name: celery-volume
          hostPath:
            path: /home/chetanyaagrawal/kalpanic/restapi  # Update with the actual path to restapi
