# Generated by Django 5.0.1 on 2024-01-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenrateVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genrated_video_url', models.URLField(default='', null=True)),
                ('image_link', models.CharField(max_length=2088)),
                ('source_video_link', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0Xn0QdJbIsUFnXi5EfoovLlk4pqnfPAWpsFMDx4YP0rvhfT0DoOw5wbf6gWUY-V6-9cE&usqp=CAU', max_length=2048, null=True),
        ),
    ]
