# Generated by Django 3.1.14 on 2024-01-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenrateVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genrated_video_url', models.URLField(default='', null=True)),
                ('image_link', models.URLField()),
                ('source_video_link', models.URLField()),
            ],
        ),
    ]
