# Generated by Django 5.0.1 on 2024-01-07 20:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("snippets", "0002_alter_searchterm_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accounts",
            old_name="Image",
            new_name="image",
        ),
        migrations.RenameField(
            model_name="accounts",
            old_name="Token",
            new_name="token",
        ),
    ]
