# Generated by Django 3.1.14 on 2024-01-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_genratevideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genratevideo',
            name='image_link',
            field=models.CharField(max_length=2088),
        ),
    ]
