name: Deploy Kalpanic

on:
  push:
    branches:
    - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v2

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v0
      with:
        # project_id: ${{ secrets.GOOGLE_PROJECT }}
        # service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        image_name: chetanyaag/ui
        tag: new
        

        export_default_credentials: true

    - name: build and push the docker image
      # env:
      #   GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        docker image build -t $image_name:$tag frontend/.
        docker login -u chetanyaag -p dckr_pat_DtBgxqDxJG2XGK5KhffuiU8XWvo
        docker push $image_name:$tag



      # gcloud auth configure-docker us-central1-docker.pkg.dev
      # docker build -t us-central1-docker.pkg.dev/$GOOGLE_PROJECT/demo/nginx:latest .
      # docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT/demo/nginx:latest