name: Build and Deploy  Kalpanic

on:
  push:
    branches:
    - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4


    - name: build and push the docker image
      env:
        image_name_frontend: ${{ secrets.IMAGE_NAME_FRONTEND }}
        image_name_backend: ${{ secrets.IMAGE_NAME_REST }}
        docker_pass: ${{ secrets.DOCKER_PASS }}

      run: |
        docker image build -t $image_name_frontend$GITHUB_SHA frontend/.
        docker image build -t $image_name_backend$GITHUB_SHA restapi/.
        docker image build -t 
        docker login -u chetanyaag -p $docker_pass
        docker push $image_name_frontend
        docker push $image_name_backend
